"""empty message

Revision ID: 35b7f19628ec
Revises: 750f6584f33f
Create Date: 2021-09-20 20:20:23.952586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35b7f19628ec'
down_revision = '750f6584f33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('nameFavorite', sa.String(length=30), nullable=False),
    sa.Column('typeFavorite', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_table('favorite')
    # ### end Alembic commands ###
