"""empty message

Revision ID: ec27ecdc2847
Revises: 35b7f19628ec
Create Date: 2021-09-20 21:04:12.058686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec27ecdc2847'
down_revision = '35b7f19628ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('user_id', sa.String(length=120), nullable=True))
    op.drop_constraint('favorite_ibfk_1', 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'])
    op.drop_column('favorite', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('owner', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_ibfk_1', 'favorite', 'user', ['owner'], ['email'])
    op.drop_column('favorite', 'user_id')
    # ### end Alembic commands ###
